version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '10:00'
    open-pull-requests-limit: 10
    groups:
      dev-deps:
        dependency-type: development
      prod-deps:
        dependency-type: production
